import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Silk from "@/components/Silk";
import {ThemeProvider} from "next-themes";
import ClickSpark from "@/components/ClickSpark";
import SplashCursor from "@/components/SplashCursor";
import MinimalNavbar from "@/components/Navbar";
import {ScrollArea, ScrollBar} from "@/components/ui/scroll-area";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "dragondevs",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-hidden`}
		>
		<ThemeProvider
			attribute="class"
			defaultTheme="dark"
			enableSystem
			disableTransitionOnChange
		>
			{/*<SplashCursor />*/}
			<div className="fixed inset-0 opacity-50 -z-50 pointer-events-none">
				<Silk
					speed={1.5}
					scale={0.7}
					color="#52525b"
					noiseIntensity={10}
					rotation={0}
				/>
			</div>
			<ClickSpark
				sparkColor='#fff'
				sparkSize={10}
				sparkRadius={25}
				sparkCount={10}
				duration={700}
			>
				<ScrollArea className="w-screen h-screen">
					{children}
					<ScrollBar className="opacity-50"/>
				</ScrollArea>
			</ClickSpark>
			<MinimalNavbar/>
		</ThemeProvider>
		</body>
		</html>
	);
}
